### ISSUE TITLE
netflix not working

### ISSUE THREAD

**Issue by proflylab** [jtvberg/StreamDock#1]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/27909158/99485188-8e0c4700-2994-11eb-93d9-72920fabe6fe.png">

**Comment by jtvberg** [comment]
Did you build and VMP sign the package using EVS?
Are other services working?
Are you located in the US?

**Comment by jtvberg** [comment]
I see you are in Taiwan. I am not certain this works outside of the US. Locality constraints may come into play. 
Other question, are you on Windows or Mac? I don't have scripts in there for Windows to VMP sign post code signing.
This is my miss. I should have included that in the README. After my next merge I will have added Windows support to to the build scripts. You can add this on your own, of course.
